name: "Docker Image Update Checker"
description: "Check if the base Docker image needs to be updated"
author: Luca Comellini <lucacome>

inputs:
  base-image:
    description: "Docker base image"
    required: true
  image:
    description: "Docker image"
    required: true
outputs:
  needs-updating:
    description: "True or false"
    value: ${{ steps.run-script.outputs.result }}
runs:
  using: "composite"
  steps:
    - id: run-script
      run: |
        result=$(base=${{ inputs.base-image }} image=${{ inputs.image }} ${{ github.action_path }}/docker.sh)
        echo "::set-output name=result::${result}"
      shell: bash

branding:
  icon: anchor
  color: blue
