name: "Docker Image Update Checker"
description: "GitHub Action to check if the base Docker image that your image is based on was updated and your image needs to be updated"
author: Luca Comellini <lucacome>

inputs:
  ghcr_user:
    description: "GitHub Username"
    required: false
  ghcr_token:
    description: "GitHub Personal Access Token"
    required: false
  target:
    description: "Docker Base Image"
    required: true
  upstream:
    description: "Docker Image"
    required: true
outputs:
  needs-updating:
    description: "True or false"
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    ghcr_user: ${{ inputs.ghcr_user }}
    ghcr_token: ${{ inputs.ghcr_token }}
    target: ${{ inputs.target }}
    upstream: ${{ inputs.upstream }}
      
branding:
  icon: anchor
  color: blue
