name: "Docker Image Update Checker"
description: "GitHub Action to check if the base Docker image that your image is based on was updated and your image needs to be updated"
author: Luca Comellini <lucacome>

inputs:
  gh-user:
    description: "GitHub Username"
    required: false
  gh-token:
    description: "GitHub Personal Access Token"
    required: false
  base-image:
    description: "Docker base image"
    required: true
  image:
    description: "Docker image"
    required: true
outputs:
  needs-updating:
    description: "True or false"
    value: ${{ steps.run-script.outputs.result }}
runs:
  using: "composite"
  steps:
    - name: Compare Versions
      id: run-script
      run: |
        result=$( \
          ghcr_user=${{ inputs.gh-user }} \
          ghcr_token=${{ inputs.gh-token }} \
          base=${{ inputs.base-image }} \
          image=${{ inputs.image }} \
          ${{ github.action_path }}/docker.sh \
        )
        echo "::set-output name=result::${result}"
      shell: bash

branding:
  icon: anchor
  color: blue
